package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * Reads patient data from output files generated by HealthDataSimulator
 * using the --output file:<output_dir> argument.
 * Each line format: patientId,timestamp,recordType,measurementValue
 */
public class FileDataReader implements DataReader {
    private final String outputDirectory;

    public FileDataReader(String outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File dir = new File(outputDirectory);
        File[] files = dir.listFiles();
        if (files == null) return;

        for (File file : files) {
            try (BufferedReader reader = 
                     new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    parseLine(line, dataStorage);
                }
            }
        }
    }

    private void parseLine(String line, DataStorage dataStorage) {
        // Expected: patientId,timestamp,recordType,measurementValue
        try {
            String[] parts = line.split(",");
            int patientId     = Integer.parseInt(parts[0].trim());
            long timestamp    = Long.parseLong(parts[1].trim());
            String recordType = parts[2].trim();
            double value      = Double.parseDouble(parts[3].trim());
            dataStorage.addPatientData(patientId, value, recordType, timestamp);
        } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
            System.err.println("Skipping malformed line: " + line);
        }
    }
}